### ISSUE TITLE
searchBy на вход должен принимать предикат

### ISSUE THREAD

**Issue by coursar** [akram8008/Avito#2]
https://github.com/akram8008/Avito/blob/47eb09fc5f9b1d1f2a48ff85e70af4397409c99e/Houses.go#L48-L55

**Comment by akram8008** [comment]
Здравствуйте, insertNeededPart func(result *[]house) - это и есть предикатная функция для searchBy например для :
func searchByMaxPrice (Houses []house, limit int64)[]house{
	return searchBy(func(result *[]house){
		for _,val:=range Houses {
			if val.price < limit {
				*result = append(*result,val)
			}
		}
	})
}

Работу предикатную функцию я сам пишу как надо работать внутри func searchByMaxPrice()

**Comment by akram8008** [comment]
Спасибо за замечание....Много думал и выявил что проход по элементам это тоже можно сократить..... И ноконецта написал и очень удобно и коротко получился.....Спасибо вам за все...... Пожалуйста если время будет проверьте еще раз ))))

**Comment by coursar** [comment]
Надо не ответы писать, а закрывать issue
